---
title: "GDPUSAvar"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Los datos provienen de la web oficial (http://www.bea.gov/national/index.htm) y corresponden a la variación porcentual respecto al periodo anterior del producto interior bruto de los Estados Unidos, basado en precios encadenados, desde el primer trimestre de 1990 hasta el último de 2017 (últimos 28 años).
La serie está ajustada estacionalmente.


```{r}
(serie=ts((read.table("gdpUSAvar.dat",header=F)),start=1990,freq=4))
plot(serie)
abline(v=1990:2018,col=4,lty=3)
abline(h=0)
```

```{r}
boxplot(serie~floor(time(serie)))
```

```{r}
plot(serie)
abline(h=0)
```

```{r}
d1serie=diff(serie)
plot(d1serie)
abline(h=0)
```

```{r}
var(serie)
var(d1serie)
```


```{r}
par(mfrow=c(1,2))
acf(serie,ylim=c(-1,1),lag.max=60,col=c(2,rep(1,3)))
pacf(serie,ylim=c(-1,1),lag.max=60,col=c(rep(1,3),2))
par(mfrow=c(1,1))
```


```{r}
#################Validation#################################
validation=function(model,dades){
  s=frequency(get(model$series))
  resid=model$residuals
  par(mfrow=c(2,2),mar=c(3,3,3,3))
  #Residuals plot
  plot(resid,main="Residuals")
  abline(h=0)
  abline(h=c(-3*sd(resid),3*sd(resid)),lty=3,col=4)
  #Square Root of absolute values of residuals (Homocedasticity)
  scatter.smooth(sqrt(abs(resid)),main="Square Root of Absolute residuals",
                 lpars=list(col=2))
  
  #Normal plot of residuals
  qqnorm(resid)
  qqline(resid,col=2,lwd=2)
  
  ##Histogram of residuals with normal curve
  hist(resid,breaks=20,freq=F)
  curve(dnorm(x,mean=mean(resid),sd=sd(resid)),col=2,add=T)
  
  
  #ACF & PACF of residuals
  par(mfrow=c(1,2))
  acf(resid,ylim=c(-1,1),lag.max=60,col=c(2,rep(1,s-1)),lwd=1)
  pacf(resid,ylim=c(-1,1),lag.max=60,col=c(rep(1,s-1),2),lwd=1)
  par(mfrow=c(1,1))
  
  #ACF & PACF of square residuals 
  par(mfrow=c(1,2))
  acf(resid^2,ylim=c(-1,1),lag.max=60,col=c(2,rep(1,s-1)),lwd=1)
  pacf(resid^2,ylim=c(-1,1),lag.max=60,col=c(rep(1,s-1),2),lwd=1)
  par(mfrow=c(1,1))
    
  #Ljung-Box p-values
  par(mar=c(2,2,1,1))
  tsdiag(model,gof.lag=7*s)
  cat("\n--------------------------------------------------------------------\n")
  print(model)
  
  #Stationary and Invertible
  cat("\nModul of AR Characteristic polynomial Roots: ", 
      Mod(polyroot(c(1,-model$model$phi))),"\n")
  cat("\nModul of MA Characteristic polynomial Roots: ",
      Mod(polyroot(c(1,model$model$theta))),"\n")
  
  #Model expressed as an MA infinity (psi-weights)
  psis=ARMAtoMA(ar=model$model$phi,ma=model$model$theta,lag.max=36)
  names(psis)=paste("psi",1:36)
  cat("\nPsi-weights (MA(inf))\n")
  cat("\n--------------------\n")
  print(psis[1:20])
  
  #Model expressed as an AR infinity (pi-weights)
  pis=-ARMAtoMA(ar=-model$model$theta,ma=-model$model$phi,lag.max=36)
  names(pis)=paste("pi",1:36)
  cat("\nPi-weights (AR(inf))\n")
  cat("\n--------------------\n")
  print(pis[1:20])
  
  ##Shapiro-Wilks Normality test
  print(shapiro.test(resid(mod)))
  
  #Sample ACF vs. Teoric ACF
  par(mfrow=c(2,2),mar=c(3,3,3,3))
  acf(dades, ylim=c(-1,1) ,lag.max=36,main="Sample ACF")
  
  plot(ARMAacf(model$model$phi,model$model$theta,lag.max=36),ylim=c(-1,1), 
       type="h",xlab="Lag",  ylab="", main="ACF Teoric")
  abline(h=0)
  
  #Sample PACF vs. Teoric PACF
  pacf(dades, ylim=c(-1,1) ,lag.max=36,main="Sample PACF")
  
  plot(ARMAacf(model$model$phi,model$model$theta,lag.max=36, pacf=T),ylim=c(-1,1),
       type="h", xlab="Lag", ylab="", main="PACF Teoric")
  abline(h=0)
  par(mfrow=c(1,1))
}
################# Fi Validació #################################
```

```{r}
(mod=arima(serie,order=c(2,0,0)))
```

```{r}
dades=serie
model=mod
validation(model,dades)
```

```{r}
(mod=arima(serie,order=c(0,0,2)))
```

```{r}
dades=serie
model=mod
validation(model,dades)
```

```{r}
(mod=arima(serie,order=c(1,0,1)))
```

```{r}
dades=serie
model=mod
validation(model,dades)
```
